# Generated by Django 5.2.5 on 2025-08-26 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0003_alter_file_options_alter_requirement_options_and_more'),
        ('user', '0021_alter_organizationuser_options_alter_student_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', '负责人'), ('member', '成员')], max_length=20, verbose_name='角色')),
                ('status', models.CharField(choices=[('pending', '申请中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('left', '已退出')], default='pending', max_length=20, verbose_name='状态')),
                ('application_message', models.TextField(blank=True, verbose_name='申请留言')),
                ('review_message', models.TextField(blank=True, verbose_name='审核留言')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_participations', to='user.student', verbose_name='审核人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participations', to='user.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '02-项目参与者',
                'verbose_name_plural': '02-项目参与者',
                'db_table': 'student_project_participant',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目标题')),
                ('description', models.TextField(verbose_name='项目描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('recruiting', '招募中'), ('in_progress', '进行中'), ('completed', '已完成'), ('suspended', '已暂停'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='项目状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('participants', models.ManyToManyField(related_name='joined_projects', through='studentproject.ProjectParticipant', through_fields=('project', 'student'), to='user.student', verbose_name='参与学生')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_projects', to='project.requirement', verbose_name='关联需求')),
            ],
            options={
                'verbose_name': '01-学生项目',
                'verbose_name_plural': '01-学生项目',
                'db_table': 'student_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectparticipant',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participants', to='studentproject.studentproject', verbose_name='项目'),
        ),
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='邀请状态')),
                ('invitation_message', models.TextField(blank=True, verbose_name='邀请留言')),
                ('response_message', models.TextField(blank=True, verbose_name='响应留言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='邀请时间')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='响应时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='user.student', verbose_name='被邀请者')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='user.student', verbose_name='邀请者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='studentproject.studentproject', verbose_name='项目')),
            ],
            options={
                'verbose_name': '06-项目邀请',
                'verbose_name_plural': '06-项目邀请',
                'db_table': 'student_project_invitation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='成果标题')),
                ('description', models.TextField(verbose_name='成果描述')),
                ('stage_type', models.CharField(choices=[('early', '前期'), ('middle', '中期'), ('final', '末期')], max_length=50, verbose_name='项目阶段')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='阶段内版本号')),
                ('stage_version', models.CharField(help_text='自动生成的易读版本标识，如：前期v1、中期v2、末期v1', max_length=100, verbose_name='阶段版本标识')),
                ('is_milestone', models.BooleanField(default=False, verbose_name='是否为里程碑版本')),
                ('progress_description', models.TextField(blank=True, help_text='描述本次提交相比上一版本的改进和进展', verbose_name='进展描述')),
                ('is_updated', models.BooleanField(default=False, help_text='标识该成果是否在初次提交后被修改过', verbose_name='是否被更新过')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('notes', models.TextField(blank=True, help_text='其他需要说明的信息', verbose_name='备注')),
                ('is_deprecated', models.BooleanField(default=False, help_text='标识该成果是否已被弃用，弃用的成果不会被删除但会被标记', verbose_name='是否已弃用')),
                ('files', models.ManyToManyField(blank=True, related_name='deliverables', to='project.file', verbose_name='关联文件')),
                ('last_modifier', models.ForeignKey(blank=True, help_text='记录最后一次修改成果的用户，初次提交时为空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_deliverables', to='user.student', verbose_name='最新修改人')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_deliverables', to='user.student', verbose_name='提交人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='studentproject.studentproject', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '03-项目成果',
                'verbose_name_plural': '03-项目成果',
                'db_table': 'student_project_deliverable',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论作者')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='studentproject.projectcomment', verbose_name='父评论')),
                ('deliverable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='studentproject.projectdeliverable', verbose_name='关联成果')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='studentproject.studentproject', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '04-项目评价',
                'verbose_name_plural': '04-项目评价',
                'db_table': 'student_project_comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('project_application', '项目申请'), ('application_approved', '申请通过'), ('application_rejected', '申请拒绝'), ('member_joined', '成员加入'), ('member_left', '成员退出'), ('deliverable_submitted', '成果提交'), ('new_comment', '新评论'), ('comment_reply', '评论回复'), ('project_status_changed', '项目状态变更'), ('role_changed', '角色变更'), ('project_invitation', '项目邀请'), ('invitation_accepted', '邀请已接受'), ('invitation_rejected', '邀请已拒绝')], max_length=50, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='studentproject.projectcomment', verbose_name='关联评论')),
                ('deliverable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='studentproject.projectdeliverable', verbose_name='关联成果')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='studentproject.studentproject', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '05-通知',
                'verbose_name_plural': '05-通知',
                'db_table': 'student_project_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentproject',
            index=models.Index(fields=['requirement'], name='student_pro_require_0cce9b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentproject',
            index=models.Index(fields=['status'], name='student_pro_status_83d0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='studentproject',
            index=models.Index(fields=['created_at'], name='student_pro_created_b74e73_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipant',
            index=models.Index(fields=['project', 'role'], name='student_pro_project_d9c830_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipant',
            index=models.Index(fields=['student'], name='student_pro_student_2c43b5_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipant',
            index=models.Index(fields=['status'], name='student_pro_status_18de93_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectparticipant',
            unique_together={('project', 'student')},
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['project'], name='student_pro_project_be96e6_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['inviter'], name='student_pro_inviter_ceb4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['invitee'], name='student_pro_invitee_d1f71f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['status'], name='student_pro_status_253565_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['created_at'], name='student_pro_created_12aec0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectinvitation',
            unique_together={('project', 'invitee')},
        ),
        migrations.AddIndex(
            model_name='projectdeliverable',
            index=models.Index(fields=['project', 'stage_type'], name='student_pro_project_a6b0ba_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdeliverable',
            index=models.Index(fields=['submitter'], name='student_pro_submitt_13ce76_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdeliverable',
            index=models.Index(fields=['created_at'], name='student_pro_created_9bfd05_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdeliverable',
            index=models.Index(fields=['is_milestone'], name='student_pro_is_mile_2bdf10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectdeliverable',
            unique_together={('project', 'stage_type', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['project'], name='student_pro_project_0aa886_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['deliverable'], name='student_pro_deliver_54f563_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['author'], name='student_pro_author__5f9e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['parent_comment'], name='student_pro_parent__10172c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['created_at'], name='student_pro_created_b48d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='student_pro_recipie_a9a033_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='student_pro_notific_2daa13_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='student_pro_created_6a6528_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['project'], name='student_pro_project_c3b42d_idx'),
        ),
    ]
