# Generated by Django 5.2.5 on 2025-09-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '04-项目评价',
                'verbose_name_plural': '04-项目评价',
                'db_table': 'student_project_comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='成果标题')),
                ('description', models.TextField(verbose_name='成果描述')),
                ('stage_type', models.CharField(choices=[('early', '前期'), ('middle', '中期'), ('final', '末期')], max_length=50, verbose_name='项目阶段')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='阶段内版本号')),
                ('stage_version', models.CharField(help_text='自动生成的易读版本标识，如：前期v1、中期v2、末期v1', max_length=100, verbose_name='阶段版本标识')),
                ('is_milestone', models.BooleanField(default=False, verbose_name='是否为里程碑版本')),
                ('progress_description', models.TextField(blank=True, help_text='描述本次提交相比上一版本的改进和进展', verbose_name='进展描述')),
                ('is_updated', models.BooleanField(default=False, help_text='标识该成果是否在初次提交后被修改过', verbose_name='是否被更新过')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('notes', models.TextField(blank=True, help_text='其他需要说明的信息', verbose_name='备注')),
                ('is_deprecated', models.BooleanField(default=False, help_text='标识该成果是否已被弃用，弃用的成果不会被删除但会被标记', verbose_name='是否已弃用')),
            ],
            options={
                'verbose_name': '03-项目成果',
                'verbose_name_plural': '03-项目成果',
                'db_table': 'student_project_deliverable',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='邀请状态')),
                ('invitation_message', models.TextField(blank=True, verbose_name='邀请留言')),
                ('response_message', models.TextField(blank=True, verbose_name='响应留言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='邀请时间')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='响应时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '06-项目邀请',
                'verbose_name_plural': '06-项目邀请',
                'db_table': 'student_project_invitation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', '负责人'), ('member', '成员')], max_length=20, verbose_name='角色')),
                ('status', models.CharField(choices=[('pending', '申请中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('left', '已退出')], default='pending', max_length=20, verbose_name='状态')),
                ('application_message', models.TextField(blank=True, verbose_name='申请留言')),
                ('review_message', models.TextField(blank=True, verbose_name='审核留言')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
            ],
            options={
                'verbose_name': '02-项目参与者',
                'verbose_name_plural': '02-项目参与者',
                'db_table': 'student_project_participant',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目标题')),
                ('description', models.TextField(verbose_name='项目描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('recruiting', '招募中'), ('in_progress', '进行中'), ('completed', '已完成'), ('suspended', '已暂停'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='项目状态')),
                ('is_evaluated', models.BooleanField(default=False, help_text='标识该项目是否已有评分记录', verbose_name='是否已评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '01-学生项目',
                'verbose_name_plural': '01-学生项目',
                'db_table': 'student_project',
                'ordering': ['-created_at'],
            },
        ),
    ]
