# Generated by Django 5.2.5 on 2025-08-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_requirement_evaluation_criteria_and_more'),
        ('studentproject', '0001_initial'),
        ('user', '0022_remove_tag2_tag_2_post_a2db1b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='is_evaluated',
            field=models.BooleanField(default=False, help_text='标识该项目是否已有评分记录', verbose_name='是否已评分'),
        ),
        migrations.AddIndex(
            model_name='studentproject',
            index=models.Index(fields=['is_evaluated'], name='student_pro_is_eval_2f83dc_idx'),
        ),
    ]
