# Generated by Django 5.2.5 on 2025-09-13 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0003_initial'),
        ('studentproject', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论作者'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='studentproject.projectcomment', verbose_name='父评论'),
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='deliverables', to='project.file', verbose_name='关联文件'),
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='last_modifier',
            field=models.ForeignKey(blank=True, help_text='记录最后一次修改成果的用户，初次提交时为空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_deliverables', to='user.student', verbose_name='最新修改人'),
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_deliverables', to='user.student', verbose_name='提交人'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='deliverable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='studentproject.projectdeliverable', verbose_name='关联成果'),
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='user.student', verbose_name='被邀请者'),
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='user.student', verbose_name='邀请者'),
        ),
        migrations.AddField(
            model_name='projectparticipant',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_participations', to='user.student', verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='projectparticipant',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participations', to='user.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='participants',
            field=models.ManyToManyField(related_name='joined_projects', through='studentproject.ProjectParticipant', through_fields=('project', 'student'), to='user.student', verbose_name='参与学生'),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_projects', to='project.requirement', verbose_name='关联需求'),
        ),
        migrations.AddField(
            model_name='projectparticipant',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participants', to='studentproject.studentproject', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='studentproject.studentproject', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='studentproject.studentproject', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='studentproject.studentproject', verbose_name='关联项目'),
        ),
        migrations.AddIndex(
            model_name='studentproject',
            index=models.Index(fields=['requirement'], name='student_pro_require_0cce9b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentproject',
            index=models.Index(fields=['status'], name='student_pro_status_83d0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='studentproject',
            index=models.Index(fields=['is_evaluated'], name='student_pro_is_eval_2f83dc_idx'),
        ),
        migrations.AddIndex(
            model_name='studentproject',
            index=models.Index(fields=['created_at'], name='student_pro_created_b74e73_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipant',
            index=models.Index(fields=['project', 'role'], name='student_pro_project_d9c830_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipant',
            index=models.Index(fields=['student'], name='student_pro_student_2c43b5_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipant',
            index=models.Index(fields=['status'], name='student_pro_status_18de93_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectparticipant',
            unique_together={('project', 'student')},
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['project'], name='student_pro_project_be96e6_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['inviter'], name='student_pro_inviter_ceb4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['invitee'], name='student_pro_invitee_d1f71f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['status'], name='student_pro_status_253565_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['created_at'], name='student_pro_created_12aec0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectinvitation',
            unique_together={('project', 'invitee')},
        ),
        migrations.AddIndex(
            model_name='projectdeliverable',
            index=models.Index(fields=['project', 'stage_type'], name='student_pro_project_a6b0ba_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdeliverable',
            index=models.Index(fields=['submitter'], name='student_pro_submitt_13ce76_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdeliverable',
            index=models.Index(fields=['created_at'], name='student_pro_created_9bfd05_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdeliverable',
            index=models.Index(fields=['is_milestone'], name='student_pro_is_mile_2bdf10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectdeliverable',
            unique_together={('project', 'stage_type', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['project'], name='student_pro_project_0aa886_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['deliverable'], name='student_pro_deliver_54f563_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['author'], name='student_pro_author__5f9e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['parent_comment'], name='student_pro_parent__10172c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['created_at'], name='student_pro_created_b48d4b_idx'),
        ),
    ]
