# Generated by Django 5.2.5 on 2025-09-26 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_initial'),
        ('studentproject', '0002_initial'),
        ('user', '0003_remove_tag1stumatch_tag1_stu_tag1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projectcomment',
            name='student_pro_project_0aa886_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectcomment',
            name='student_pro_deliver_54f563_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectcomment',
            name='student_pro_author__5f9e4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectcomment',
            name='student_pro_created_b48d4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectdeliverable',
            name='student_pro_project_a6b0ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectdeliverable',
            name='student_pro_submitt_13ce76_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectdeliverable',
            name='student_pro_created_9bfd05_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectdeliverable',
            name='student_pro_is_mile_2bdf10_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectinvitation',
            name='student_pro_project_be96e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectinvitation',
            name='student_pro_inviter_ceb4a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectinvitation',
            name='student_pro_invitee_d1f71f_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectinvitation',
            name='student_pro_status_253565_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectinvitation',
            name='student_pro_created_12aec0_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectparticipant',
            name='student_pro_project_d9c830_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectparticipant',
            name='student_pro_student_2c43b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectparticipant',
            name='student_pro_status_18de93_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentproject',
            name='student_pro_require_0cce9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentproject',
            name='student_pro_status_83d0f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentproject',
            name='student_pro_is_eval_2f83dc_idx',
        ),
        migrations.RenameIndex(
            model_name='projectcomment',
            new_name='pc_parent_idx',
            old_name='student_pro_parent__10172c_idx',
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['project', 'deliverable'], name='pc_proj_deliverable_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['author', 'created_at'], name='pc_author_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdeliverable',
            index=models.Index(fields=['project', 'stage_type', 'is_milestone'], name='pd_proj_stage_milestone_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdeliverable',
            index=models.Index(fields=['submitter', 'created_at'], name='pd_submitter_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['project', 'status'], name='pi_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['invitee', 'status'], name='pi_invitee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['inviter', 'created_at'], name='pi_inviter_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipant',
            index=models.Index(fields=['project', 'role', 'status'], name='pp_proj_role_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipant',
            index=models.Index(fields=['student', 'status'], name='pp_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentproject',
            index=models.Index(fields=['requirement', 'status'], name='sp_req_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentproject',
            index=models.Index(fields=['status', 'is_evaluated'], name='sp_status_eval_idx'),
        ),
    ]
