# Generated by Django 5.2.5 on 2025-09-26 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_requirementfavorite_req_fav_student_idx_and_more'),
        ('studentproject', '0003_remove_projectcomment_student_pro_project_0aa886_idx_and_more'),
        ('user', '0005_alter_tag2_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomment',
            name='author',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论作者'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='project',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='studentproject.studentproject', verbose_name='关联项目'),
        ),
        migrations.AlterField(
            model_name='projectdeliverable',
            name='project',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='studentproject.studentproject', verbose_name='关联项目'),
        ),
        migrations.AlterField(
            model_name='projectdeliverable',
            name='submitter',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_deliverables', to='user.student', verbose_name='提交人'),
        ),
        migrations.AlterField(
            model_name='projectinvitation',
            name='invitee',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='user.student', verbose_name='被邀请者'),
        ),
        migrations.AlterField(
            model_name='projectinvitation',
            name='inviter',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='user.student', verbose_name='邀请者'),
        ),
        migrations.AlterField(
            model_name='projectinvitation',
            name='project',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='studentproject.studentproject', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='projectparticipant',
            name='project',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='project_participants', to='studentproject.studentproject', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='projectparticipant',
            name='student',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='project_participations', to='user.student', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='requirement',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_projects', to='project.requirement', verbose_name='关联需求'),
        ),
    ]
