# Generated by Django 5.2.5 on 2025-09-13 07:59

import django.db.models.deletion
import organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('member_approve', '审核通过成员'), ('member_reject', '拒绝成员申请'), ('member_suspend', '暂停成员'), ('member_activate', '激活成员'), ('member_reactivate', '重新激活成员'), ('member_remove', '移除成员'), ('member_status_update', '更新成员状态'), ('permission_grant_admin', '授予管理员权限'), ('permission_revoke_admin', '撤销管理员权限'), ('permission_grant_member', '授予成员权限'), ('permission_revoke_member', '撤销成员权限'), ('organization_update', '更新组织信息'), ('organization_config_update', '更新组织配置'), ('verification_materials_submit', '提交认证材料')], max_length=30, verbose_name='操作类型')),
                ('details', models.JSONField(blank=True, default=dict, help_text='存储操作的详细信息', verbose_name='操作详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '02-组织操作日志',
                'verbose_name_plural': '02-组织操作日志',
                'db_table': 'organization_operation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=100, unique=True, verbose_name='学校名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '04-高等学校',
                'verbose_name_plural': '04-高等学校',
                'db_table': 'university',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_type', models.CharField(choices=[('enterprise', '企业'), ('university', '大学'), ('other', '其他组织')], max_length=20, verbose_name='组织类型')),
                ('name', models.CharField(max_length=200, verbose_name='组织名称')),
                ('code', models.CharField(blank=True, help_text='企业：统一社会信用代码；大学：教育部代码；其他：相关证照编号', max_length=50, null=True, unique=True, verbose_name='组织代码')),
                ('leader_name', models.CharField(blank=True, help_text='企业：法定代表人；大学：校长；其他：主要负责人', max_length=50, verbose_name='负责人姓名')),
                ('leader_title', models.CharField(blank=True, max_length=50, verbose_name='负责人职务')),
                ('enterprise_type', models.CharField(blank=True, choices=[('state_owned', '国有企业'), ('private', '民营企业'), ('foreign', '外资企业'), ('joint_venture', '合资企业'), ('startup', '创业公司'), ('listed', '上市公司'), ('other', '其他')], max_length=20, null=True, verbose_name='企业类型')),
                ('university_type', models.CharField(blank=True, choices=[('985', '985工程'), ('211', '211工程'), ('double_first_class', '双一流'), ('ordinary', '普通本科'), ('vocational', '高职专科'), ('independent', '独立学院'), ('private_university', '民办大学')], max_length=20, null=True, verbose_name='大学类型')),
                ('other_type', models.CharField(blank=True, choices=[('government', '政府机构'), ('ngo', '非营利组织'), ('foundation', '基金会'), ('association', '行业协会'), ('research_institute', '科研院所'), ('hospital', '医疗机构'), ('media', '媒体机构'), ('cultural', '文化机构'), ('sports', '体育组织'), ('religious', '宗教组织'), ('international', '国际组织'), ('community', '社区组织'), ('cooperative', '合作社'), ('union', '工会组织'), ('chamber', '商会'), ('other', '其他未分类')], max_length=30, null=True, verbose_name='其他组织类型')),
                ('organization_nature', models.CharField(blank=True, choices=[('public', '公立/公办'), ('private', '私立/民办'), ('joint', '公私合营'), ('international', '国际性'), ('regional', '地区性'), ('national', '全国性')], max_length=20, null=True, verbose_name='组织性质')),
                ('industry_or_discipline', models.CharField(help_text='企业：所属行业；大学：主要学科门类；其他：业务领域', max_length=100, verbose_name='行业/学科领域')),
                ('scale', models.CharField(choices=[('small', '小型（1-500人）'), ('medium', '中型（501-2000人）'), ('large', '大型（2001-10000人）'), ('giant', '超大型（10000人以上）')], max_length=20, verbose_name='规模')),
                ('business_scope', models.CharField(blank=True, help_text='描述组织的主要业务范围或服务领域', max_length=200, verbose_name='业务范围/服务领域')),
                ('regulatory_authority', models.CharField(blank=True, help_text='如：民政部、卫健委、教育部等', max_length=100, verbose_name='监管机构')),
                ('license_info', models.TextField(blank=True, help_text='相关的许可证号、资质证书等信息', verbose_name='许可证/资质信息')),
                ('service_target', models.CharField(blank=True, choices=[('public', '面向公众'), ('members', '面向会员'), ('industry', '面向行业'), ('government', '面向政府'), ('enterprises', '面向企业'), ('students', '面向学生'), ('patients', '面向患者'), ('community', '面向社区'), ('other', '其他')], max_length=20, null=True, verbose_name='主要服务对象')),
                ('contact_person', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_position', models.CharField(blank=True, max_length=50, verbose_name='联系人职位')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('address', models.TextField(verbose_name='详细地址')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='邮政编码')),
                ('description', models.TextField(blank=True, verbose_name='组织简介')),
                ('website', models.URLField(blank=True, verbose_name='官方网站')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=organization.models.organization_logo_upload_path, verbose_name='组织标识')),
                ('status', models.CharField(choices=[('pending', '待认证'), ('under_review', '审核中'), ('verified', '已认证'), ('rejected', '认证被拒'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='认证时间')),
                ('verification_comment', models.TextField(blank=True, help_text='管理员审核时的意见，通过时可填写"通过"，拒绝时需注明具体原因', verbose_name='认证意见')),
                ('verification_image', models.JSONField(blank=True, default=list, help_text='组织认证时提交的图片证明材料，最多5张，至少1张', verbose_name='认证图片')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='成立时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '01-组织',
                'verbose_name_plural': '01-组织',
                'db_table': 'organization',
                'indexes': [models.Index(fields=['organization_type'], name='organizatio_organiz_b4644e_idx'), models.Index(fields=['name'], name='organizatio_name_bcc2ee_idx'), models.Index(fields=['code'], name='organizatio_code_9ea172_idx'), models.Index(fields=['industry_or_discipline'], name='organizatio_industr_365166_idx'), models.Index(fields=['scale'], name='organizatio_scale_860a62_idx'), models.Index(fields=['status'], name='organizatio_status_3d172d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve_members', models.BooleanField(default=False, help_text='是否自动审核新成员申请', verbose_name='自动审核成员')),
                ('require_email_verification', models.BooleanField(default=True, help_text='新成员是否需要邮箱验证', verbose_name='需要邮箱验证')),
                ('allow_member_invite', models.BooleanField(default=False, help_text='普通成员是否可以邀请新成员', verbose_name='允许成员邀请')),
                ('admin_can_manage_admins', models.BooleanField(default=False, help_text='管理员是否可以管理其他管理员', verbose_name='管理员可管理管理员')),
                ('member_can_view_all', models.BooleanField(default=True, help_text='普通成员是否可以查看所有成员信息', verbose_name='成员可查看全部')),
                ('max_members', models.PositiveIntegerField(default=1000, help_text='组织最大成员数量限制', verbose_name='最大成员数')),
                ('welcome_message', models.TextField(blank=True, help_text='新成员加入时的欢迎消息', verbose_name='欢迎消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='organization.organization', verbose_name='组织')),
            ],
            options={
                'verbose_name': '03-组织配置',
                'verbose_name_plural': '03-组织配置',
                'db_table': 'organization_config',
            },
        ),
    ]
