# Generated by Django 5.2.5 on 2025-09-13 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationoperationlog',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作者'),
        ),
        migrations.AddField(
            model_name='organizationoperationlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='organization.organization', verbose_name='组织'),
        ),
        migrations.AddField(
            model_name='organizationoperationlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_operation_targets', to=settings.AUTH_USER_MODEL, verbose_name='目标用户'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['school'], name='university_school_70c1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationoperationlog',
            index=models.Index(fields=['organization', 'created_at'], name='organizatio_organiz_be8999_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationoperationlog',
            index=models.Index(fields=['operator', 'created_at'], name='organizatio_operato_e5d31c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationoperationlog',
            index=models.Index(fields=['operation'], name='organizatio_operati_1ab0f7_idx'),
        ),
    ]
