# Generated by Django 5.1.7 on 2025-08-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationoperationlog",
            name="operation",
            field=models.CharField(
                choices=[
                    ("member_approve", "审核通过成员"),
                    ("member_reject", "拒绝成员申请"),
                    ("member_suspend", "暂停成员"),
                    ("member_activate", "激活成员"),
                    ("member_remove", "移除成员"),
                    ("permission_grant_admin", "授予管理员权限"),
                    ("permission_revoke_admin", "撤销管理员权限"),
                    ("permission_grant_member", "授予成员权限"),
                    ("permission_revoke_member", "撤销成员权限"),
                    ("organization_update", "更新组织信息"),
                    ("organization_config_update", "更新组织配置"),
                ],
                max_length=30,
                verbose_name="操作类型",
            ),
        ),
    ]
