# Generated by Django 5.2.5 on 2025-08-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organizationoperationlog_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='business_scope',
            field=models.CharField(blank=True, help_text='描述组织的主要业务范围或服务领域', max_length=200, verbose_name='业务范围/服务领域'),
        ),
        migrations.AddField(
            model_name='organization',
            name='license_info',
            field=models.TextField(blank=True, help_text='相关的许可证号、资质证书等信息', verbose_name='许可证/资质信息'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_nature',
            field=models.CharField(blank=True, choices=[('public', '公立/公办'), ('private', '私立/民办'), ('joint', '公私合营'), ('international', '国际性'), ('regional', '地区性'), ('national', '全国性')], max_length=20, null=True, verbose_name='组织性质'),
        ),
        migrations.AddField(
            model_name='organization',
            name='other_type',
            field=models.CharField(blank=True, choices=[('government', '政府机构'), ('ngo', '非营利组织'), ('foundation', '基金会'), ('association', '行业协会'), ('research_institute', '科研院所'), ('hospital', '医疗机构'), ('media', '媒体机构'), ('cultural', '文化机构'), ('sports', '体育组织'), ('religious', '宗教组织'), ('international', '国际组织'), ('community', '社区组织'), ('cooperative', '合作社'), ('union', '工会组织'), ('chamber', '商会'), ('other_unspecified', '其他未分类')], max_length=30, null=True, verbose_name='其他组织类型'),
        ),
        migrations.AddField(
            model_name='organization',
            name='regulatory_authority',
            field=models.CharField(blank=True, help_text='如：民政部、卫健委、教育部等', max_length=100, verbose_name='监管机构'),
        ),
        migrations.AddField(
            model_name='organization',
            name='service_target',
            field=models.CharField(blank=True, choices=[('public', '面向公众'), ('members', '面向会员'), ('industry', '面向行业'), ('government', '面向政府'), ('enterprises', '面向企业'), ('students', '面向学生'), ('patients', '面向患者'), ('community', '面向社区'), ('other', '其他')], max_length=20, null=True, verbose_name='主要服务对象'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, help_text='企业：统一社会信用代码；大学：教育部代码；其他：相关证照编号', max_length=50, null=True, unique=True, verbose_name='组织代码'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry_or_discipline',
            field=models.CharField(help_text='企业：所属行业；大学：主要学科门类；其他：业务领域', max_length=100, verbose_name='行业/学科领域'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='leader_name',
            field=models.CharField(blank=True, help_text='企业：法定代表人；大学：校长；其他：主要负责人', max_length=50, verbose_name='负责人姓名'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('enterprise', '企业'), ('university', '大学'), ('other', '其他组织')], max_length=20, verbose_name='组织类型'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_number',
            field=models.CharField(blank=True, help_text='企业：工商注册号；大学：办学许可证号；其他：登记证号', max_length=50, verbose_name='注册号'),
        ),
    ]
