# Generated by Django 5.2.5 on 2025-10-25 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationoperationlog',
            name='operation',
            field=models.CharField(choices=[('member_approve', '审核通过成员'), ('member_reject', '拒绝成员申请'), ('member_invite', '邀请成员'), ('member_suspend', '暂停成员'), ('member_activate', '激活成员'), ('member_reactivate', '重新激活成员'), ('member_remove', '移除成员'), ('member_status_update', '更新成员状态'), ('member_leave', '成员退出组织'), ('permission_grant_admin', '授予管理员权限'), ('permission_revoke_admin', '撤销管理员权限'), ('permission_grant_member', '授予成员权限'), ('permission_revoke_member', '撤销成员权限'), ('organization_update', '更新组织信息'), ('organization_config_update', '更新组织配置'), ('verification_materials_submit', '提交认证材料'), ('join_application_submit', '提交加入申请'), ('join_application_approve', '批准加入申请'), ('join_application_reject', '拒绝加入申请'), ('join_application_cancel', '取消加入申请'), ('invitation_code_join', '通过邀请码加入')], max_length=30, verbose_name='操作类型'),
        ),
        migrations.CreateModel(
            name='OrganizationJoinApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_reason', models.TextField(help_text='用户申请加入组织的理由说明', verbose_name='申请理由')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='申请状态')),
                ('review_comment', models.TextField(blank=True, help_text='审核人的意见或拒绝理由', verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_applications', to='organization.organization', verbose_name='目标组织')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '05-组织加入申请',
                'verbose_name_plural': '05-组织加入申请',
                'db_table': 'organization_join_application',
                'indexes': [models.Index(fields=['applicant', 'status'], name='organizatio_applica_8461a5_idx'), models.Index(fields=['organization', 'status'], name='organizatio_organiz_94c9ae_idx'), models.Index(fields=['status', 'created_at'], name='organizatio_status_6af0fb_idx')],
                'unique_together': {('applicant', 'organization', 'status')},
            },
        ),
    ]
