# Generated by Django 5.2.5 on 2025-08-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_business_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='verification_image',
            field=models.JSONField(blank=True, default=list, help_text='组织认证时提交的图片证明材料，最多5张，至少1张', verbose_name='认证图片'),
        ),
        migrations.AlterField(
            model_name='organizationoperationlog',
            name='operation',
            field=models.CharField(choices=[('member_approve', '审核通过成员'), ('member_reject', '拒绝成员申请'), ('member_suspend', '暂停成员'), ('member_activate', '激活成员'), ('member_reactivate', '重新激活成员'), ('member_remove', '移除成员'), ('member_status_update', '更新成员状态'), ('permission_grant_admin', '授予管理员权限'), ('permission_revoke_admin', '撤销管理员权限'), ('permission_grant_member', '授予成员权限'), ('permission_revoke_member', '撤销成员权限'), ('organization_update', '更新组织信息'), ('organization_config_update', '更新组织配置')], max_length=30, verbose_name='操作类型'),
        ),
    ]
