# Generated by Django 5.2.5 on 2025-08-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_verification_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='other_type',
            field=models.CharField(blank=True, choices=[('government', '政府机构'), ('ngo', '非营利组织'), ('foundation', '基金会'), ('association', '行业协会'), ('research_institute', '科研院所'), ('hospital', '医疗机构'), ('media', '媒体机构'), ('cultural', '文化机构'), ('sports', '体育组织'), ('religious', '宗教组织'), ('international', '国际组织'), ('community', '社区组织'), ('cooperative', '合作社'), ('union', '工会组织'), ('chamber', '商会'), ('other', '其他未分类')], max_length=30, null=True, verbose_name='其他组织类型'),
        ),
        migrations.AlterField(
            model_name='organizationoperationlog',
            name='operation',
            field=models.CharField(choices=[('member_approve', '审核通过成员'), ('member_reject', '拒绝成员申请'), ('member_suspend', '暂停成员'), ('member_activate', '激活成员'), ('member_reactivate', '重新激活成员'), ('member_remove', '移除成员'), ('member_status_update', '更新成员状态'), ('permission_grant_admin', '授予管理员权限'), ('permission_revoke_admin', '撤销管理员权限'), ('permission_grant_member', '授予成员权限'), ('permission_revoke_member', '撤销成员权限'), ('organization_update', '更新组织信息'), ('organization_config_update', '更新组织配置'), ('verification_materials_submit', '提交认证材料')], max_length=30, verbose_name='操作类型'),
        ),
    ]
