# Generated by Django 5.2.5 on 2025-08-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_add_verification_materials_submit_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='registration_number',
        ),
    ]
