# Generated by Django 5.2.5 on 2025-08-26 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_remove_registration_number_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': '01-组织', 'verbose_name_plural': '01-组织'},
        ),
        migrations.AlterModelOptions(
            name='organizationconfig',
            options={'verbose_name': '03-组织配置', 'verbose_name_plural': '03-组织配置'},
        ),
        migrations.AlterModelOptions(
            name='organizationoperationlog',
            options={'ordering': ['-created_at'], 'verbose_name': '02-组织操作日志', 'verbose_name_plural': '02-组织操作日志'},
        ),
    ]
