# Generated by Django 5.2.5 on 2025-09-29 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CASAuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas_user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='CAS用户ID')),
                ('action', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('validate', '票据验证')], max_length=20, verbose_name='操作类型')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('pending', '处理中')], max_length=20, verbose_name='状态')),
                ('ticket', models.CharField(blank=True, max_length=500, null=True, verbose_name='CAS票据')),
                ('service_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='服务URL')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('response_data', models.JSONField(blank=True, help_text='CAS服务器返回的原始数据', null=True, verbose_name='响应数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, help_text='认证成功后关联的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': 'CAS认证日志',
                'verbose_name_plural': 'CAS认证日志',
                'db_table': 'cas_auth_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='cas_auth_lo_user_id_341fcc_idx'), models.Index(fields=['cas_user_id', 'created_at'], name='cas_auth_lo_cas_use_2d8244_idx'), models.Index(fields=['status', 'action'], name='cas_auth_lo_status_add6f9_idx'), models.Index(fields=['created_at'], name='cas_auth_lo_created_62c423_idx')],
            },
        ),
    ]
