# Generated by Django 5.2.5 on 2025-09-13 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('skipped', '跳过')], max_length=20, verbose_name='操作结果')),
                ('message', models.TextField(blank=True, verbose_name='日志消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '05-通知日志',
                'verbose_name_plural': '05-通知日志',
                'db_table': 'notification_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_websocket', models.BooleanField(default=True, verbose_name='启用实时通知')),
                ('enable_email', models.BooleanField(default=False, verbose_name='启用邮件通知')),
                ('enable_sms', models.BooleanField(default=False, verbose_name='启用短信通知')),
                ('type_preferences', models.JSONField(blank=True, default=dict, verbose_name='类型偏好设置')),
                ('quiet_start_time', models.TimeField(blank=True, null=True, verbose_name='免打扰开始时间')),
                ('quiet_end_time', models.TimeField(blank=True, null=True, verbose_name='免打扰结束时间')),
                ('do_not_disturb', models.BooleanField(default=False, verbose_name='一键免打扰')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '04-通知偏好设置',
                'verbose_name_plural': '04-通知偏好设置',
                'db_table': 'notification_preference',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_template', models.CharField(max_length=200, verbose_name='标题模板')),
                ('content_template', models.TextField(verbose_name='内容模板')),
                ('email_subject', models.CharField(blank=True, max_length=200, verbose_name='邮件主题模板')),
                ('email_content', models.TextField(blank=True, verbose_name='邮件内容模板')),
                ('sms_content', models.TextField(blank=True, verbose_name='短信内容模板')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='模板变量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '03-通知模板',
                'verbose_name_plural': '03-通知模板',
                'db_table': 'notification_template',
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='类型代码')),
                ('name', models.CharField(max_length=100, verbose_name='类型名称')),
                ('category', models.CharField(choices=[('system', '系统通知'), ('project', '项目通知'), ('organization', '组织通知'), ('user', '用户通知')], max_length=20, verbose_name='通知分类')),
                ('description', models.TextField(blank=True, verbose_name='类型描述')),
                ('default_template', models.TextField(blank=True, verbose_name='默认消息模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '02-通知类型',
                'verbose_name_plural': '02-通知类型',
                'db_table': 'notification_type',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('read', '已读'), ('failed', '发送失败')], default='pending', max_length=10, verbose_name='状态')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='关联对象类型')),
            ],
            options={
                'verbose_name': '01-通知详情',
                'verbose_name_plural': '01-通知详情',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
