# Generated by Django 5.2.5 on 2025-09-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagMatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('student_id', models.PositiveIntegerField(db_column='Sid', db_index=True, help_text='关联的学生用户ID', verbose_name='学生ID')),
                ('requirement_id', models.PositiveIntegerField(db_column='Pid', db_index=True, help_text='关联的项目需求ID', verbose_name='项目需求ID')),
                ('tag_source', models.CharField(blank=True, choices=[('tag1', '兴趣标签'), ('tag2', '能力标签')], db_column='Msource', help_text='标签来源类型：tag1为兴趣标签，tag2为能力标签', max_length=10, null=True, verbose_name='标签来源')),
                ('tag_id', models.PositiveIntegerField(blank=True, help_text='对应标签表中的ID', null=True, verbose_name='标签ID')),
            ],
            options={
                'verbose_name': '标签匹配',
                'verbose_name_plural': '标签匹配',
                'db_table': 'tag_match',
                'indexes': [models.Index(fields=['student_id'], name='tag_match_student_idx'), models.Index(fields=['requirement_id'], name='tag_match_requirement_idx'), models.Index(fields=['tag_source'], name='tag_match_source_idx'), models.Index(fields=['tag_id'], name='tag_match_tag_id_idx'), models.Index(fields=['student_id', 'tag_source'], name='tag_match_stu_source_idx'), models.Index(fields=['requirement_id', 'tag_source'], name='tag_match_req_source_idx'), models.Index(fields=['student_id', 'requirement_id'], name='tag_match_stu_req_idx'), models.Index(fields=['tag_source', 'tag_id'], name='tag_match_source_tag_idx')],
                'unique_together': {('student_id', 'requirement_id', 'tag_source', 'tag_id')},
            },
        ),
    ]
