# Generated by Django 5.2.5 on 2025-09-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tagmatch',
            name='tag_match_student_idx',
        ),
        migrations.RemoveIndex(
            model_name='tagmatch',
            name='tag_match_requirement_idx',
        ),
        migrations.RemoveIndex(
            model_name='tagmatch',
            name='tag_match_source_idx',
        ),
        migrations.RemoveIndex(
            model_name='tagmatch',
            name='tag_match_tag_id_idx',
        ),
        migrations.AlterField(
            model_name='tagmatch',
            name='requirement_id',
            field=models.PositiveIntegerField(db_column='Pid', help_text='关联的项目需求ID', verbose_name='项目需求ID'),
        ),
        migrations.AlterField(
            model_name='tagmatch',
            name='student_id',
            field=models.PositiveIntegerField(db_column='Sid', help_text='关联的学生用户ID', verbose_name='学生ID'),
        ),
    ]
