# Generated by Django 5.2.5 on 2025-09-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_search', '0002_remove_tagmatch_tag_match_student_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tagmatch',
            name='tag_match_stu_req_idx',
        ),
    ]
