# Generated by Django 5.2.5 on 2025-09-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_type', models.CharField(choices=[('password', '密码登录'), ('email_code', '邮箱验证码登录'), ('phone_code', '手机验证码登录'), ('wechat', '微信登录'), ('qq', 'QQ登录'), ('register', '注册')], max_length=20, verbose_name='登录方式')),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('is_success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '01-账户登录日志',
                'verbose_name_plural': '01-账户登录日志',
                'db_table': 'login_log',
            },
        ),
        migrations.CreateModel(
            name='AccountDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('email', models.CharField(max_length=254, verbose_name='邮箱')),
                ('user_type', models.CharField(max_length=20, verbose_name='用户类型')),
                ('deletion_type', models.CharField(choices=[('user_request', '用户主动注销'), ('admin_action', '管理员操作'), ('system_cleanup', '系统清理'), ('violation', '违规处理')], max_length=20, verbose_name='注销类型')),
                ('reason', models.TextField(blank=True, verbose_name='注销原因')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已批准'), ('rejected', '已拒绝'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='处理状态')),
                ('requested_by', models.IntegerField(blank=True, null=True, verbose_name='申请人ID')),
                ('processed_by', models.IntegerField(blank=True, null=True, verbose_name='处理人ID')),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('data_backup_path', models.CharField(blank=True, max_length=500, verbose_name='数据备份路径')),
                ('is_data_anonymized', models.BooleanField(default=False, verbose_name='是否已匿名化')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('scheduled_deletion_at', models.DateTimeField(blank=True, null=True, verbose_name='计划删除时间')),
                ('actual_deletion_at', models.DateTimeField(blank=True, null=True, verbose_name='实际删除时间')),
            ],
            options={
                'verbose_name': '02-账户注销日志',
                'verbose_name_plural': '02-账户注销日志',
                'db_table': 'account_deletion_log',
                'indexes': [models.Index(fields=['user_id'], name='account_del_user_id_b34a75_idx'), models.Index(fields=['status'], name='account_del_status_da3974_idx'), models.Index(fields=['requested_at'], name='account_del_request_b99422_idx'), models.Index(fields=['scheduled_deletion_at'], name='account_del_schedul_837326_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
                ('code_type', models.CharField(choices=[('register', '注册验证码'), ('login', '登录验证码'), ('reset_password', '重置密码验证码'), ('change_email', '更换邮箱验证码'), ('delete_account', '账户注销验证码')], max_length=20, verbose_name='验证码类型')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '00-邮箱验证码',
                'verbose_name_plural': '00-邮箱验证码',
                'db_table': 'email_verification_code',
                'indexes': [models.Index(fields=['email', 'code_type'], name='email_verif_email_8fc993_idx'), models.Index(fields=['created_at'], name='email_verif_created_7e2ab0_idx'), models.Index(fields=['expires_at'], name='email_verif_expires_c1cad4_idx')],
            },
        ),
    ]
