# Generated by Django 5.1.7 on 2025-08-07 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loginlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="loginlog",
            index=models.Index(
                fields=["user", "created_at"], name="login_log_user_id_d8012e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginlog",
            index=models.Index(
                fields=["ip_address"], name="login_log_ip_addr_56ff59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginlog",
            index=models.Index(
                fields=["created_at"], name="login_log_created_cd8ea9_idx"
            ),
        ),
    ]
