# Generated by Django 5.2.5 on 2025-10-25 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('organization', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='邀请码')),
                ('status', models.CharField(choices=[('active', '有效'), ('expired', '已过期'), ('disabled', '已禁用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('max_uses', models.PositiveIntegerField(default=100, help_text='0表示无限制', verbose_name='最大使用次数')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invitation_codes', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='organization.organization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '03-企业邀请码',
                'verbose_name_plural': '03-企业邀请码',
                'db_table': 'organization_invitation_code',
                'indexes': [models.Index(fields=['organization', 'status'], name='organizatio_organiz_1a49ab_idx'), models.Index(fields=['code'], name='organizatio_code_662fb7_idx'), models.Index(fields=['expires_at'], name='organizatio_expires_8f196b_idx'), models.Index(fields=['created_at'], name='organizatio_created_7b7ad0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('organization',), name='unique_active_invitation_per_org')],
            },
        ),
    ]
