# Generated by Django 5.2.5 on 2025-08-26 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountdeletionlog',
            options={'verbose_name': '02-账户注销日志', 'verbose_name_plural': '02-账户注销日志'},
        ),
        migrations.AlterModelOptions(
            name='emailverificationcode',
            options={'verbose_name': '00-邮箱验证码', 'verbose_name_plural': '00-邮箱验证码'},
        ),
        migrations.AlterModelOptions(
            name='loginlog',
            options={'verbose_name': '01-账户登录日志', 'verbose_name_plural': '01-账户登录日志'},
        ),
    ]
