# Generated by Django 5.2.5 on 2025-10-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_organizationinvitationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvitationcode',
            name='expired_notification_sent',
            field=models.BooleanField(default=False, verbose_name='已过期通知已发送'),
        ),
        migrations.AddField(
            model_name='organizationinvitationcode',
            name='expiry_notification_sent',
            field=models.BooleanField(default=False, verbose_name='即将过期通知已发送'),
        ),
        migrations.AddField(
            model_name='organizationinvitationcode',
            name='last_used_notification_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后使用通知时间'),
        ),
    ]
