# Generated by Django 5.2.5 on 2025-10-25 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_organizationinvitationcode_expired_notification_sent_and_more'),
    ]

    operations = [
    ]
