# Generated by Django 5.2.5 on 2025-09-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submit', '提交认证'), ('approve', '认证通过'), ('reject', '认证拒绝'), ('resubmit', '重新提交'), ('update_materials', '更新材料'), ('withdraw', '撤回申请'), ('auto_approve', '自动通过'), ('batch_approve', '批量通过'), ('batch_reject', '批量拒绝'), ('suspend', '暂停认证'), ('restore', '恢复认证')], max_length=20, verbose_name='审核操作')),
                ('status_transition', models.CharField(blank=True, choices=[('pending_to_under_review', '待认证 → 审核中'), ('under_review_to_verified', '审核中 → 已认证'), ('under_review_to_rejected', '审核中 → 认证被拒'), ('rejected_to_under_review', '认证被拒 → 重新审核'), ('verified_to_closed', '已认证 → 已关闭'), ('closed_to_verified', '已关闭 → 已认证')], max_length=30, null=True, verbose_name='状态变更')),
                ('old_status', models.CharField(blank=True, help_text='变更前的组织认证状态', max_length=20, verbose_name='原状态')),
                ('new_status', models.CharField(help_text='变更后的组织认证状态', max_length=20, verbose_name='新状态')),
                ('operator_role', models.CharField(choices=[('admin', '系统管理员'), ('org_owner', '组织所有者'), ('org_admin', '组织管理员'), ('applicant', '申请人'), ('system', '系统自动')], help_text='操作者在此次审核中的角色', max_length=20, verbose_name='操作者角色')),
                ('comment', models.TextField(blank=True, help_text='审核时的具体意见或理由', verbose_name='审核意见')),
                ('review_details', models.JSONField(blank=True, default=dict, help_text='存储审核的详细信息，如修改的字段、提交的材料等', verbose_name='审核详情')),
                ('submitted_materials', models.JSONField(blank=True, default=list, help_text='本次提交或更新的认证材料信息', verbose_name='提交材料')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '组织认证审核历史日志',
                'verbose_name_plural': '组织认证审核历史日志',
                'db_table': 'organization_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementAuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submit', '提交审核'), ('approve', '审核通过'), ('reject', '审核拒绝'), ('resubmit', '重新提交'), ('withdraw', '撤回申请'), ('auto_approve', '自动通过'), ('batch_approve', '批量通过'), ('batch_reject', '批量拒绝')], max_length=20, verbose_name='审核操作')),
                ('status_transition', models.CharField(blank=True, choices=[('pending_to_under_review', '待审核 → 审核中'), ('under_review_to_approved', '审核中 → 通过'), ('under_review_to_rejected', '审核中 → 拒绝'), ('rejected_to_under_review', '拒绝 → 重新审核'), ('approved_to_in_progress', '通过 → 进行中'), ('in_progress_to_completed', '进行中 → 已完成'), ('in_progress_to_paused', '进行中 → 已暂停'), ('paused_to_in_progress', '已暂停 → 进行中')], max_length=30, null=True, verbose_name='状态变更')),
                ('old_status', models.CharField(blank=True, help_text='变更前的需求状态', max_length=20, verbose_name='原状态')),
                ('new_status', models.CharField(help_text='变更后的需求状态', max_length=20, verbose_name='新状态')),
                ('operator_role', models.CharField(choices=[('admin', '系统管理员'), ('org_owner', '组织所有者'), ('org_admin', '组织管理员'), ('publisher', '需求发布者'), ('system', '系统自动')], help_text='操作者在此次审核中的角色', max_length=20, verbose_name='操作者角色')),
                ('comment', models.TextField(blank=True, help_text='审核时的具体意见或理由', verbose_name='审核意见')),
                ('review_details', models.JSONField(blank=True, default=dict, help_text='存储审核的详细信息，如修改的字段、附加数据等', verbose_name='审核详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '需求审核历史日志',
                'verbose_name_plural': '需求审核历史日志',
                'db_table': 'requirement_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
