# Generated by Django 5.2.5 on 2025-09-13 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('organization', '0001_initial'),
        ('project', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationauditlog',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_audit_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作者'),
        ),
        migrations.AddField(
            model_name='organizationauditlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organization.organization', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='requirementauditlog',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_audit_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作者'),
        ),
        migrations.AddField(
            model_name='requirementauditlog',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='project.requirement', verbose_name='关联需求'),
        ),
        migrations.AddIndex(
            model_name='organizationauditlog',
            index=models.Index(fields=['organization', 'created_at'], name='organizatio_organiz_73e40e_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationauditlog',
            index=models.Index(fields=['operator', 'created_at'], name='organizatio_operato_2d4db4_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationauditlog',
            index=models.Index(fields=['action'], name='organizatio_action_bf88fe_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationauditlog',
            index=models.Index(fields=['new_status'], name='organizatio_new_sta_c389e5_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationauditlog',
            index=models.Index(fields=['organization', 'action'], name='organizatio_organiz_f89ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationauditlog',
            index=models.Index(fields=['created_at'], name='organizatio_created_3e5991_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementauditlog',
            index=models.Index(fields=['requirement', 'created_at'], name='requirement_require_4d0b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementauditlog',
            index=models.Index(fields=['operator', 'created_at'], name='requirement_operato_5a3b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementauditlog',
            index=models.Index(fields=['action'], name='requirement_action_bd9038_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementauditlog',
            index=models.Index(fields=['new_status'], name='requirement_new_sta_641490_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementauditlog',
            index=models.Index(fields=['requirement', 'action'], name='requirement_require_eb3ada_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementauditlog',
            index=models.Index(fields=['created_at'], name='requirement_created_56ef21_idx'),
        ),
    ]
