# Generated by Django 5.2.5 on 2025-08-18 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0005_add_verification_materials_submit_operation'),
        ('user', '0014_remove_tag2_tag_2_post_a2db1b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, help_text='文件的完整URL下载地址', verbose_name='完整下载地址')),
                ('name', models.CharField(max_length=255, verbose_name='文件/文件夹名称')),
                ('path', models.CharField(blank=True, help_text='虚拟文件系统中的路径，如：/项目文档/设计图/logo.png', max_length=500, verbose_name='虚拟路径')),
                ('real_path', models.CharField(blank=True, help_text='文件在服务器上的实际存储路径，文件夹为null', max_length=500, null=True, verbose_name='实际存储路径')),
                ('parent_path', models.CharField(blank=True, help_text='父级文件夹的虚拟路径', max_length=500, null=True, verbose_name='父级虚拟路径')),
                ('is_folder', models.BooleanField(default=False, help_text='True表示文件夹，False表示文件', verbose_name='是否为文件夹')),
                ('size', models.BigIntegerField(default=0, verbose_name='文件大小（字节）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间戳')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间戳')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('type', models.CharField(choices=[('code', '代码'), ('dataset', '数据集'), ('document', '文档'), ('course', '课程'), ('video', '视频'), ('tool', '工具')], max_length=50, verbose_name='类型')),
                ('status', models.CharField(choices=[('published', '已发布'), ('under_review', '审核中'), ('draft', '草稿'), ('unpublished', '已下线')], max_length=50, verbose_name='状态')),
                ('downloads', models.CharField(default='0', max_length=255, verbose_name='下载数')),
                ('views', models.CharField(default='0', max_length=255, verbose_name='浏览数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间戳')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间戳')),
                ('create_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_resources', to='user.organizationuser', verbose_name='创建人')),
                ('files', models.ManyToManyField(blank=True, to='project.file', verbose_name='文件信息')),
                ('tag1', models.ManyToManyField(blank=True, to='user.tag1', verbose_name='兴趣标签')),
                ('tag2', models.ManyToManyField(blank=True, to='user.tag2', verbose_name='能力标签')),
                ('update_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_resources', to='user.organizationuser', verbose_name='更新人')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('brief', models.CharField(max_length=255, verbose_name='简介')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('status', models.CharField(choices=[('under_review', '审核中'), ('review_failed', '审核失败'), ('recruiting', '招募中'), ('in_progress', '进行中'), ('completed', '已完成'), ('paused', '已暂停')], max_length=50, verbose_name='状态')),
                ('finish_time', models.DateField(blank=True, null=True, verbose_name='完成时间')),
                ('budget', models.CharField(max_length=255, verbose_name='预算')),
                ('people_count', models.CharField(max_length=255, verbose_name='人数需求')),
                ('applications', models.IntegerField(default=0, verbose_name='申请数')),
                ('joined_count', models.IntegerField(default=0, verbose_name='已加入人数')),
                ('views', models.IntegerField(default=0, verbose_name='浏览数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('files', models.ManyToManyField(blank=True, to='project.file', verbose_name='文件信息')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='组织')),
                ('publish_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.organizationuser', verbose_name='发布人')),
                ('tag1', models.ManyToManyField(blank=True, to='user.tag1', verbose_name='兴趣标签')),
                ('tag2', models.ManyToManyField(blank=True, to='user.tag2', verbose_name='能力标签')),
                ('resources', models.ManyToManyField(blank=True, to='project.resource', verbose_name='关联资源')),
            ],
            options={
                'verbose_name': '需求',
                'verbose_name_plural': '需求',
                'ordering': ['-created_at'],
            },
        ),
    ]
