# Generated by Django 5.2.5 on 2025-09-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, help_text='文件的完整URL下载地址', verbose_name='完整下载地址')),
                ('name', models.CharField(max_length=255, verbose_name='文件/文件夹名称')),
                ('path', models.CharField(blank=True, help_text='虚拟文件系统中的路径，如：/项目文档/设计图/logo.png', max_length=500, verbose_name='虚拟路径')),
                ('real_path', models.CharField(blank=True, help_text='文件在服务器上的实际存储路径，文件夹为null', max_length=500, null=True, verbose_name='实际存储路径')),
                ('parent_path', models.CharField(blank=True, help_text='父级文件夹的虚拟路径', max_length=500, null=True, verbose_name='父级虚拟路径')),
                ('is_folder', models.BooleanField(default=False, help_text='True表示文件夹，False表示文件', verbose_name='是否为文件夹')),
                ('is_cloud_link', models.BooleanField(default=False, help_text='True表示网盘链接文件，False表示普通文件', verbose_name='是否为网盘链接')),
                ('cloud_password', models.CharField(blank=True, help_text='网盘链接的提取密码', max_length=100, null=True, verbose_name='网盘链接密码')),
                ('size', models.BigIntegerField(default=0, verbose_name='文件大小（字节）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间戳')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间戳')),
            ],
            options={
                'verbose_name': '01-文件',
                'verbose_name_plural': '01-文件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('brief', models.CharField(max_length=255, verbose_name='简介')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('status', models.CharField(choices=[('under_review', '审核中'), ('review_failed', '审核失败'), ('in_progress', '进行中'), ('completed', '已完成'), ('paused', '已暂停')], max_length=50, verbose_name='状态')),
                ('finish_time', models.DateField(blank=True, null=True, verbose_name='完成时间')),
                ('budget', models.CharField(blank=True, max_length=255, null=True, verbose_name='预算')),
                ('people_count', models.CharField(blank=True, max_length=255, null=True, verbose_name='人数需求')),
                ('support_provided', models.TextField(blank=True, null=True, verbose_name='可提供的支持')),
                ('evaluation_published', models.BooleanField(default=False, help_text='标记该需求下的项目评分是否已公示', verbose_name='评分已公示')),
                ('review_comment', models.TextField(blank=True, help_text='管理员审核时的意见，审核通过时可填写"通过"，审核失败时需注明具体原因', verbose_name='审核意见')),
                ('views', models.IntegerField(default=0, verbose_name='浏览数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '02-需求',
                'verbose_name_plural': '02-需求',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementFavorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '04-需求收藏',
                'verbose_name_plural': '04-需求收藏',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('type', models.CharField(choices=[('code', '代码'), ('dataset', '数据集'), ('document', '文档'), ('course', '课程'), ('video', '视频'), ('tool', '工具')], max_length=50, verbose_name='类型')),
                ('status', models.CharField(choices=[('published', '已发布'), ('draft', '草稿'), ('unpublished', '已下线')], max_length=50, verbose_name='状态')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='下载数')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间戳')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间戳')),
            ],
            options={
                'verbose_name': '03-资源',
                'verbose_name_plural': '03-资源',
                'ordering': ['-created_at'],
            },
        ),
    ]
