# Generated by Django 5.2.5 on 2025-09-13 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('project', '0001_initial'),
        ('projectscore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='evaluation_criteria',
            field=models.ForeignKey(blank=True, help_text='关联的评分标准，用于项目评分', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements_using_criteria', to='projectscore.evaluationcriteria', verbose_name='评分标准'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='files',
            field=models.ManyToManyField(blank=True, to='project.file', verbose_name='文件信息'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='组织'),
        ),
    ]
