# Generated by Django 5.2.5 on 2025-08-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_remove_registration_number_field'),
        ('project', '0001_initial'),
        ('user', '0015_remove_tag2_tag_2_post_a2db1b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='support_provided',
            field=models.TextField(blank=True, null=True, verbose_name='可提供的支持'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='budget',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='预算'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='people_count',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='人数需求'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('under_review', '审核中'), ('review_failed', '审核失败'), ('in_progress', '进行中'), ('completed', '已完成'), ('paused', '已暂停')], max_length=50, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='downloads',
            field=models.PositiveIntegerField(default=0, verbose_name='下载数'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('published', '已发布'), ('draft', '草稿'), ('unpublished', '已下线')], max_length=50, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览数'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['status'], name='req_status_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['organization'], name='req_org_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['created_at'], name='req_created_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['views'], name='req_views_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['title'], name='req_title_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['status', 'created_at'], name='req_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['organization', 'status'], name='req_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['organization', 'created_at'], name='req_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['status', 'organization', 'created_at'], name='req_status_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['-views'], name='req_views_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['-created_at'], name='req_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status'], name='res_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['type'], name='res_type_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['create_person'], name='res_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['created_at'], name='res_created_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['title'], name='res_title_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['downloads'], name='res_downloads_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['views'], name='res_views_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status', 'created_at'], name='res_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['create_person', 'status'], name='res_creator_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['create_person', 'created_at'], name='res_creator_created_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['-downloads'], name='res_downloads_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['-views'], name='res_views_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['-created_at'], name='res_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status', 'created_at', 'downloads'], name='res_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status', 'created_at', 'views'], name='res_stat_views_idx'),
        ),
    ]
