# Generated by Django 5.2.5 on 2025-08-26 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_requirement_support_provided_and_more'),
        ('user', '0021_alter_organizationuser_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created_at'], 'verbose_name': '01-文件', 'verbose_name_plural': '01-文件'},
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['-created_at'], 'verbose_name': '02-需求', 'verbose_name_plural': '02-需求'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_at'], 'verbose_name': '03-资源', 'verbose_name_plural': '03-资源'},
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='joined_count',
        ),
        migrations.AddField(
            model_name='file',
            name='cloud_password',
            field=models.CharField(blank=True, help_text='网盘链接的提取密码', max_length=100, null=True, verbose_name='网盘链接密码'),
        ),
        migrations.AddField(
            model_name='file',
            name='is_cloud_link',
            field=models.BooleanField(default=False, help_text='True表示网盘链接文件，False表示普通文件', verbose_name='是否为网盘链接'),
        ),
        migrations.CreateModel(
            name='RequirementFavorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.requirement', verbose_name='需求')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='学生用户')),
            ],
            options={
                'verbose_name': '04-需求收藏',
                'verbose_name_plural': '04-需求收藏',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student'], name='req_fav_student_idx'), models.Index(fields=['requirement'], name='req_fav_req_idx'), models.Index(fields=['student', 'created_at'], name='req_fav_student_created_idx')],
                'unique_together': {('student', 'requirement')},
            },
        ),
    ]
