# Generated by Django 5.2.5 on 2025-09-13 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='publish_people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.organizationuser', verbose_name='发布人'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='tag1',
            field=models.ManyToManyField(blank=True, to='user.tag1', verbose_name='兴趣标签'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='tag2',
            field=models.ManyToManyField(blank=True, to='user.tag2', verbose_name='能力标签'),
        ),
        migrations.AddField(
            model_name='requirementfavorite',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.requirement', verbose_name='需求'),
        ),
        migrations.AddField(
            model_name='requirementfavorite',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='学生用户'),
        ),
        migrations.AddField(
            model_name='resource',
            name='create_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_resources', to='user.organizationuser', verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='resource',
            name='files',
            field=models.ManyToManyField(blank=True, to='project.file', verbose_name='文件信息'),
        ),
        migrations.AddField(
            model_name='resource',
            name='tag1',
            field=models.ManyToManyField(blank=True, to='user.tag1', verbose_name='兴趣标签'),
        ),
        migrations.AddField(
            model_name='resource',
            name='tag2',
            field=models.ManyToManyField(blank=True, to='user.tag2', verbose_name='能力标签'),
        ),
        migrations.AddField(
            model_name='resource',
            name='update_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_resources', to='user.organizationuser', verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='resources',
            field=models.ManyToManyField(blank=True, to='project.resource', verbose_name='关联资源'),
        ),
        migrations.AddIndex(
            model_name='requirementfavorite',
            index=models.Index(fields=['student'], name='req_fav_student_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementfavorite',
            index=models.Index(fields=['requirement'], name='req_fav_req_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementfavorite',
            index=models.Index(fields=['student', 'created_at'], name='req_fav_student_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requirementfavorite',
            unique_together={('student', 'requirement')},
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status'], name='res_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['type'], name='res_type_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['create_person'], name='res_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['created_at'], name='res_created_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['title'], name='res_title_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['downloads'], name='res_downloads_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['views'], name='res_views_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status', 'created_at'], name='res_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['create_person', 'status'], name='res_creator_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['create_person', 'created_at'], name='res_creator_created_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['-downloads'], name='res_downloads_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['-views'], name='res_views_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['-created_at'], name='res_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status', 'created_at', 'downloads'], name='res_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status', 'created_at', 'views'], name='res_stat_views_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['status'], name='req_status_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['organization'], name='req_org_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['created_at'], name='req_created_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['views'], name='req_views_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['title'], name='req_title_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['evaluation_criteria'], name='req_eval_criteria_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['status', 'created_at'], name='req_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['organization', 'status'], name='req_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['organization', 'created_at'], name='req_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['status', 'organization', 'created_at'], name='req_status_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['evaluation_criteria', 'status'], name='req_eval_status_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['-views'], name='req_views_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['-created_at'], name='req_created_desc_idx'),
        ),
    ]
