# Generated by Django 5.2.5 on 2025-09-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_initial'),
        ('user', '0003_remove_tag1stumatch_tag1_stu_tag1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='requirementfavorite',
            name='req_fav_student_idx',
        ),
        migrations.RemoveIndex(
            model_name='requirementfavorite',
            name='req_fav_req_idx',
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='res_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='res_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='res_creator_idx',
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='res_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='res_title_idx',
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='res_downloads_idx',
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='res_views_idx',
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['type', 'status'], name='res_type_status_idx'),
        ),
    ]
