# Generated by Django 5.2.5 on 2025-09-13 07:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='user', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$', '用户名只能包含字母、数字和下划线')], verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '请输入正确的手机号')], verbose_name='手机号')),
                ('real_name', models.CharField(blank=True, max_length=50, verbose_name='真实姓名')),
                ('avatar', models.FileField(blank=True, null=True, upload_to=user.models.user_avatar_upload_path, verbose_name='头像')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, verbose_name='性别')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='个人简介')),
                ('user_type', models.CharField(choices=[('student', '学生'), ('organization', '组织用户'), ('admin', '管理员')], max_length=20, verbose_name='用户类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否为员工')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '01-用户总览',
                'verbose_name_plural': '01-用户总览',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, help_text='企业：职位；大学：职务（如教授、副教授、讲师等）', max_length=100, verbose_name='职位/职务')),
                ('department', models.CharField(blank=True, help_text='企业：部门；大学：院系', max_length=100, verbose_name='部门/院系')),
                ('permission', models.CharField(choices=[('owner', '所有者'), ('admin', '管理员'), ('member', '成员'), ('pending', '待审核')], default='pending', max_length=10, verbose_name='权限')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '未通过')], default='pending', max_length=20, verbose_name='认证状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organization.organization', verbose_name='所属组织')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '03-组织用户',
                'verbose_name_plural': '03-组织用户',
                'db_table': 'organization_user',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('grade', models.CharField(choices=[('2021', '2021级'), ('2022', '2022级'), ('2023', '2023级'), ('2024', '2024级'), ('2025', '2025级'), ('2026', '2026级'), ('2027', '2027级'), ('2028', '2028级')], max_length=10, verbose_name='年级')),
                ('education_level', models.CharField(choices=[('undergraduate', '本科'), ('master', '硕士'), ('doctor', '博士'), ('college', '专科')], default='undergraduate', max_length=20, verbose_name='学历层次')),
                ('status', models.CharField(choices=[('studying', '在读'), ('graduated', '已毕业'), ('suspended', '休学'), ('dropped', '退学')], default='studying', max_length=20, verbose_name='学籍状态')),
                ('expected_graduation', models.DateField(blank=True, null=True, verbose_name='预计毕业时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.university', verbose_name='学校')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '02-学生用户',
                'verbose_name_plural': '02-学生用户',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StudentKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='关键词在对应表中的ID', max_length=50, verbose_name='关键词ID')),
                ('tag_type', models.CharField(choices=[('1', '兴趣'), ('2', '能力')], help_text='1为兴趣，2为能力', max_length=1, verbose_name='标签类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '06-学生关键词',
                'verbose_name_plural': '06-学生关键词',
                'db_table': 'student_keyword',
            },
        ),
        migrations.CreateModel(
            name='Tag1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='如：大模型、人工智能等', max_length=100, unique=True, verbose_name='标签内容')),
                ('frequency', models.CharField(blank=True, max_length=255, null=True, verbose_name='频率')),
            ],
            options={
                'verbose_name': '04-兴趣标签',
                'verbose_name_plural': '04-兴趣标签',
                'db_table': 'tag_1',
                'indexes': [models.Index(fields=['value'], name='tag1_value_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tag1StuMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='学生')),
                ('tag1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tag1', verbose_name='兴趣标签')),
            ],
            options={
                'verbose_name': '07-学生兴趣标签关联',
                'verbose_name_plural': '07-学生兴趣标签关联',
                'db_table': 'tag1_stu_match',
            },
        ),
        migrations.CreateModel(
            name='Tag2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(help_text='完整的岗位描述，如：互联网-java-前端', max_length=200, verbose_name='岗位描述')),
                ('category', models.CharField(help_text='第一级分类，如：互联网、设计', max_length=100, verbose_name='行业分类')),
                ('subcategory', models.CharField(help_text='第二级分类，如：java、UI设计', max_length=100, verbose_name='技术分类')),
                ('specialty', models.CharField(blank=True, help_text='第三级分类，如：前端、后端', max_length=100, null=True, verbose_name='专业方向')),
                ('frequency', models.CharField(blank=True, max_length=255, null=True, verbose_name='频率')),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='标签层级：1=行业-技术，2=行业-技术-岗位', verbose_name='层级')),
                ('parent', models.ForeignKey(blank=True, help_text='指向父级标签，用于构建层次结构', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user.tag2', verbose_name='父级标签')),
            ],
            options={
                'verbose_name': '05-能力标签',
                'verbose_name_plural': '05-能力标签',
                'db_table': 'tag_2',
            },
        ),
        migrations.CreateModel(
            name='Tag2StuMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='学生')),
                ('tag2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tag2', verbose_name='能力标签')),
            ],
            options={
                'verbose_name': '08-学生能力标签关联',
                'verbose_name_plural': '08-学生能力标签关联',
                'db_table': 'tag2_stu_match',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_7bbb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='user_usernam_b79065_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='user_phone_3acb84_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='user_user_ty_088d91_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='user_date_jo_a134dc_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['permission'], name='org_user_perm_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['status'], name='org_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['organization'], name='org_user_org_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['organization', 'permission'], name='org_user_org_perm_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['organization', 'status'], name='org_user_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='student_student_97543b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school'], name='student_school__876486_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['major'], name='student_major_f2d2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['grade'], name='student_grade_ff2e49_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='student_status_bbc24a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentkeyword',
            index=models.Index(fields=['student', 'tag_type'], name='student_key_student_01d6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentkeyword',
            index=models.Index(fields=['tag_type'], name='student_key_tag_typ_0bbba9_idx'),
        ),
        migrations.AddIndex(
            model_name='tag1stumatch',
            index=models.Index(fields=['tag1'], name='tag1_stu_tag1_idx'),
        ),
        migrations.AddIndex(
            model_name='tag1stumatch',
            index=models.Index(fields=['student'], name='tag1_stu_student_idx'),
        ),
        migrations.AddIndex(
            model_name='tag1stumatch',
            index=models.Index(fields=['tag1', 'student'], name='tag1_stu_tag1_student_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag1stumatch',
            unique_together={('student', 'tag1')},
        ),
        migrations.AddIndex(
            model_name='tag2',
            index=models.Index(fields=['category'], name='tag2_category_idx'),
        ),
        migrations.AddIndex(
            model_name='tag2',
            index=models.Index(fields=['subcategory'], name='tag2_subcategory_idx'),
        ),
        migrations.AddIndex(
            model_name='tag2',
            index=models.Index(fields=['specialty'], name='tag2_specialty_idx'),
        ),
        migrations.AddIndex(
            model_name='tag2',
            index=models.Index(fields=['parent'], name='tag2_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='tag2',
            index=models.Index(fields=['level'], name='tag2_level_idx'),
        ),
        migrations.AddIndex(
            model_name='tag2',
            index=models.Index(fields=['category', 'subcategory'], name='tag2_cat_subcat_idx'),
        ),
        migrations.AddIndex(
            model_name='tag2',
            index=models.Index(fields=['category', 'subcategory', 'specialty'], name='tag2_full_path_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag2',
            unique_together={('category', 'subcategory', 'specialty')},
        ),
        migrations.AddIndex(
            model_name='tag2stumatch',
            index=models.Index(fields=['tag2'], name='tag2_stu_tag2_idx'),
        ),
        migrations.AddIndex(
            model_name='tag2stumatch',
            index=models.Index(fields=['student'], name='tag2_stu_student_idx'),
        ),
        migrations.AddIndex(
            model_name='tag2stumatch',
            index=models.Index(fields=['tag2', 'student'], name='tag2_stu_tag2_student_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag2stumatch',
            unique_together={('student', 'tag2')},
        ),
    ]
