# Generated by Django 5.1.7 on 2025-08-07 13:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        default="user",
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z0-9_]+$", "用户名只能包含字母、数字和下划线"
                            )
                        ],
                        verbose_name="用户名",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^1[3-9]\\d{9}$", "请输入正确的手机号"
                            )
                        ],
                        verbose_name="手机号",
                    ),
                ),
                (
                    "real_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="真实姓名"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=user.models.user_avatar_upload_path,
                        verbose_name="头像",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "男"), ("female", "女"), ("other", "其他")],
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="年龄"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="个人简介"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("student", "学生"),
                            ("organization", "组织用户"),
                            ("admin", "管理员"),
                        ],
                        max_length=20,
                        verbose_name="用户类型",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="是否为员工"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="注册时间"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后登录"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[("enterprise", "企业"), ("university", "大学")],
                        max_length=20,
                        verbose_name="组织类型",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="组织名称")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="企业：统一社会信用代码；大学：教育部代码",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="组织代码",
                    ),
                ),
                (
                    "leader_name",
                    models.CharField(
                        blank=True,
                        help_text="企业：法定代表人；大学：校长",
                        max_length=50,
                        verbose_name="负责人姓名",
                    ),
                ),
                (
                    "leader_title",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="负责人职务"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="企业：工商注册号；大学：办学许可证号",
                        max_length=50,
                        verbose_name="注册号",
                    ),
                ),
                (
                    "enterprise_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("state_owned", "国有企业"),
                            ("private", "民营企业"),
                            ("foreign", "外资企业"),
                            ("joint_venture", "合资企业"),
                            ("startup", "创业公司"),
                            ("listed", "上市公司"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="企业类型",
                    ),
                ),
                (
                    "university_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("985", "985工程"),
                            ("211", "211工程"),
                            ("double_first_class", "双一流"),
                            ("ordinary", "普通本科"),
                            ("vocational", "高职专科"),
                            ("independent", "独立学院"),
                            ("private_university", "民办大学"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="大学类型",
                    ),
                ),
                (
                    "industry_or_discipline",
                    models.CharField(
                        help_text="企业：所属行业；大学：主要学科门类",
                        max_length=100,
                        verbose_name="行业/学科领域",
                    ),
                ),
                (
                    "scale",
                    models.CharField(
                        choices=[
                            ("small", "小型（1-500人）"),
                            ("medium", "中型（501-2000人）"),
                            ("large", "大型（2001-10000人）"),
                            ("giant", "超大型（10000人以上）"),
                        ],
                        max_length=20,
                        verbose_name="规模",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=50, verbose_name="联系人"),
                ),
                (
                    "contact_position",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="联系人职位"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="联系电话"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="联系邮箱"
                    ),
                ),
                ("address", models.TextField(verbose_name="详细地址")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="邮政编码"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="组织简介")),
                ("website", models.URLField(blank=True, verbose_name="官方网站")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="organization_logos/",
                        verbose_name="组织标识",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待认证"),
                            ("under_review", "审核中"),
                            ("verified", "已认证"),
                            ("rejected", "认证被拒"),
                            ("closed", "已关闭"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="认证时间"
                    ),
                ),
                (
                    "established_date",
                    models.DateField(blank=True, null=True, verbose_name="成立时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "组织",
                "verbose_name_plural": "组织",
                "db_table": "organization",
                "indexes": [
                    models.Index(
                        fields=["organization_type"],
                        name="organizatio_organiz_b4644e_idx",
                    ),
                    models.Index(fields=["name"], name="organizatio_name_bcc2ee_idx"),
                    models.Index(fields=["code"], name="organizatio_code_9ea172_idx"),
                    models.Index(
                        fields=["industry_or_discipline"],
                        name="organizatio_industr_365166_idx",
                    ),
                    models.Index(fields=["scale"], name="organizatio_scale_860a62_idx"),
                    models.Index(
                        fields=["status"], name="organizatio_status_3d172d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="企业：职位；大学：职务（如教授、副教授、讲师等）",
                        max_length=100,
                        verbose_name="职位/职务",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="企业：部门；大学：院系",
                        max_length=100,
                        verbose_name="部门/院系",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[("admin", "管理员"), ("member", "成员")],
                        default="member",
                        max_length=10,
                        verbose_name="权限",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_verification", "待认证"),
                            ("pending", "待审核"),
                            ("active", "正常"),
                            ("suspended", "暂停"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending_verification",
                        max_length=20,
                        verbose_name="认证状态",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="user.organization",
                        verbose_name="所属组织",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "组织用户",
                "verbose_name_plural": "组织用户",
                "db_table": "organization_user",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(max_length=20, unique=True, verbose_name="学号"),
                ),
                ("school", models.CharField(max_length=100, verbose_name="学校")),
                ("major", models.CharField(max_length=100, verbose_name="专业")),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("2021", "2021级"),
                            ("2022", "2022级"),
                            ("2023", "2023级"),
                            ("2024", "2024级"),
                            ("2025", "2025级"),
                            ("2026", "2026级"),
                            ("2027", "2027级"),
                            ("2028", "2028级"),
                        ],
                        max_length=10,
                        verbose_name="年级",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("undergraduate", "本科"),
                            ("master", "硕士"),
                            ("doctor", "博士"),
                            ("college", "专科"),
                        ],
                        default="undergraduate",
                        max_length=20,
                        verbose_name="学历层次",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("studying", "在读"),
                            ("graduated", "已毕业"),
                            ("suspended", "休学"),
                            ("dropped", "退学"),
                        ],
                        default="studying",
                        max_length=20,
                        verbose_name="学籍状态",
                    ),
                ),
                (
                    "expected_graduation",
                    models.DateField(
                        blank=True, null=True, verbose_name="预计毕业时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "学生",
                "verbose_name_plural": "学生",
                "db_table": "student",
            },
        ),
        migrations.CreateModel(
            name="StudentKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        help_text="关键词在对应表中的ID",
                        max_length=50,
                        verbose_name="关键词ID",
                    ),
                ),
                (
                    "tag_type",
                    models.CharField(
                        choices=[("1", "兴趣"), ("2", "能力")],
                        help_text="1为兴趣，2为能力",
                        max_length=1,
                        verbose_name="标签类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生关键词",
                "verbose_name_plural": "学生关键词",
                "db_table": "student_keyword",
            },
        ),
        migrations.CreateModel(
            name="Tag1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="如：大模型、人工智能等",
                        max_length=100,
                        unique=True,
                        verbose_name="标签内容",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "兴趣标签",
                "verbose_name_plural": "兴趣标签",
                "db_table": "tag_1",
                "indexes": [
                    models.Index(fields=["value"], name="tag_1_value_6b2701_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Tag1StuMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
                (
                    "tag1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.tag1",
                        verbose_name="兴趣标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生兴趣标签关联",
                "verbose_name_plural": "学生兴趣标签关联",
                "db_table": "tag1_stu_match",
            },
        ),
        migrations.CreateModel(
            name="Tag2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post",
                    models.CharField(
                        help_text="如：前端、后端",
                        max_length=50,
                        verbose_name="岗位名称",
                    ),
                ),
                (
                    "subclasses",
                    models.CharField(max_length=100, verbose_name="一级分类"),
                ),
                (
                    "subdivision",
                    models.CharField(max_length=100, verbose_name="二级分类"),
                ),
                (
                    "zhuisu_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="二级分类所属一级分类的ID",
                        null=True,
                        verbose_name="追溯ID",
                    ),
                ),
                (
                    "required_number",
                    models.IntegerField(default=0, verbose_name="需求人数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "能力标签",
                "verbose_name_plural": "能力标签",
                "db_table": "tag_2",
                "indexes": [
                    models.Index(fields=["post"], name="tag_2_post_a2db1b_idx"),
                    models.Index(
                        fields=["subclasses"], name="tag_2_subclas_d05a44_idx"
                    ),
                    models.Index(fields=["zhuisu_id"], name="tag_2_zhuisu__248f08_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Tag2StuMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
                (
                    "tag2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.tag2",
                        verbose_name="能力标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生能力标签关联",
                "verbose_name_plural": "学生能力标签关联",
                "db_table": "tag2_stu_match",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="user_email_7bbb4c_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="user_usernam_b79065_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone"], name="user_phone_3acb84_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["user_type"], name="user_user_ty_088d91_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["date_joined"], name="user_date_jo_a134dc_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationuser",
            index=models.Index(
                fields=["permission"], name="organizatio_permiss_f1b3c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationuser",
            index=models.Index(fields=["status"], name="organizatio_status_c580c7_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationuser",
            index=models.Index(
                fields=["organization"], name="organizatio_organiz_270ae8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["student_id"], name="student_student_97543b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["school"], name="student_school_5152cb_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["major"], name="student_major_f2d2c0_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["grade"], name="student_grade_ff2e49_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["status"], name="student_status_bbc24a_idx"),
        ),
        migrations.AddIndex(
            model_name="studentkeyword",
            index=models.Index(
                fields=["student", "tag_type"], name="student_key_student_01d6e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentkeyword",
            index=models.Index(
                fields=["tag_type"], name="student_key_tag_typ_0bbba9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tag1stumatch",
            unique_together={("student", "tag1")},
        ),
        migrations.AlterUniqueTogether(
            name="tag2stumatch",
            unique_together={("student", "tag2")},
        ),
    ]
