# Generated by Django 5.1.7 on 2025-08-08 04:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationuser",
            name="joined_at",
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="管理员是否已认证该用户身份",
                verbose_name="是否已认证",
            ),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="permission",
            field=models.CharField(
                choices=[
                    ("owner", "所有者"),
                    ("admin", "管理员"),
                    ("member", "成员"),
                    ("pending", "待审核"),
                ],
                default="pending",
                max_length=10,
                verbose_name="权限",
            ),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("active", "正常"),
                    ("rejected", "已拒绝"),
                    ("suspended", "暂停"),
                ],
                default="pending",
                max_length=20,
                verbose_name="认证状态",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="创建时间"),
        ),
        migrations.CreateModel(
            name="OrganizationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_approve_members",
                    models.BooleanField(
                        default=False,
                        help_text="是否自动审核新成员申请",
                        verbose_name="自动审核成员",
                    ),
                ),
                (
                    "require_email_verification",
                    models.BooleanField(
                        default=True,
                        help_text="新成员是否需要邮箱验证",
                        verbose_name="需要邮箱验证",
                    ),
                ),
                (
                    "allow_member_invite",
                    models.BooleanField(
                        default=False,
                        help_text="普通成员是否可以邀请新成员",
                        verbose_name="允许成员邀请",
                    ),
                ),
                (
                    "admin_can_manage_admins",
                    models.BooleanField(
                        default=False,
                        help_text="管理员是否可以管理其他管理员",
                        verbose_name="管理员可管理管理员",
                    ),
                ),
                (
                    "member_can_view_all",
                    models.BooleanField(
                        default=True,
                        help_text="普通成员是否可以查看所有成员信息",
                        verbose_name="成员可查看全部",
                    ),
                ),
                (
                    "max_members",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="组织最大成员数量限制",
                        verbose_name="最大成员数",
                    ),
                ),
                (
                    "welcome_message",
                    models.TextField(
                        blank=True,
                        help_text="新成员加入时的欢迎消息",
                        verbose_name="欢迎消息",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="user.organization",
                        verbose_name="组织",
                    ),
                ),
            ],
            options={
                "verbose_name": "组织配置",
                "verbose_name_plural": "组织配置",
                "db_table": "organization_config",
            },
        ),
        migrations.CreateModel(
            name="OrganizationOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("member_approve", "审核通过成员"),
                            ("member_reject", "拒绝成员"),
                            ("member_suspend", "暂停成员"),
                            ("member_activate", "激活成员"),
                            ("permission_change", "权限变更"),
                            ("member_verify", "认证成员"),
                            ("member_unverify", "取消认证"),
                            ("member_remove", "移除成员"),
                            ("organization_update", "更新组织信息"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="存储操作的详细信息",
                        verbose_name="操作详情",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="用户代理")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_operations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作者",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_logs",
                        to="user.organization",
                        verbose_name="组织",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_operation_targets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="目标用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "组织操作日志",
                "verbose_name_plural": "组织操作日志",
                "db_table": "organization_operation_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"],
                        name="organizatio_organiz_be8999_idx",
                    ),
                    models.Index(
                        fields=["operator", "created_at"],
                        name="organizatio_operato_e5d31c_idx",
                    ),
                    models.Index(
                        fields=["operation"], name="organizatio_operati_1ab0f7_idx"
                    ),
                ],
            },
        ),
    ]
