# Generated by Django 5.2.5 on 2025-09-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tag1stumatch',
            name='tag1_stu_tag1_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag1stumatch',
            name='tag1_stu_student_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag2',
            name='tag2_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag2',
            name='tag2_subcategory_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag2',
            name='tag2_specialty_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag2',
            name='tag2_parent_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag2',
            name='tag2_level_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag2',
            name='tag2_cat_subcat_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag2stumatch',
            name='tag2_stu_tag2_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag2stumatch',
            name='tag2_stu_student_idx',
        ),
        migrations.AddIndex(
            model_name='tag2',
            index=models.Index(fields=['level', 'category'], name='tag2_level_category_idx'),
        ),
        migrations.AddIndex(
            model_name='tag2',
            index=models.Index(fields=['parent', 'level'], name='tag2_parent_level_idx'),
        ),
    ]
