# Generated by Django 5.2.5 on 2025-09-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
        ('user', '0003_remove_tag1stumatch_tag1_stu_tag1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organizationuser',
            name='org_user_perm_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationuser',
            name='org_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationuser',
            name='org_user_org_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='student_school__876486_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='student_major_f2d2c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='student_grade_ff2e49_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='student_status_bbc24a_idx',
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'status'], name='student_school_status_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'grade'], name='student_school_grade_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['major', 'grade'], name='student_major_grade_idx'),
        ),
    ]
