# Generated by Django 5.1.7 on 2025-08-09 02:30

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_organizationuser_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=user.models.user_avatar_upload_path,
                verbose_name="头像",
            ),
        ),
    ]