# Generated by Django 5.2.5 on 2025-09-26 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_organizationuser_org_user_perm_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag2',
            name='parent',
            field=models.ForeignKey(blank=True, db_index=False, help_text='指向父级标签，用于构建层次结构', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user.tag2', verbose_name='父级标签'),
        ),
    ]
