# Generated by Django 5.2.5 on 2025-09-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_tag2_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='auth_source',
            field=models.CharField(choices=[('manual', '手动注册'), ('cas', 'CAS认证')], default='manual', help_text='用户认证来源', max_length=20, verbose_name='认证来源'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='cas_user_id',
            field=models.CharField(blank=True, help_text='CAS系统返回的用户唯一标识', max_length=100, null=True, verbose_name='CAS用户ID'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='employee_id',
            field=models.CharField(blank=True, help_text='教师工号，用于CAS统一认证', max_length=50, null=True, verbose_name='工号'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='last_cas_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后CAS登录时间'),
        ),
    ]
