# Generated by Django 5.2.5 on 2025-08-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_organizationuser_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationoperationlog',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationconfig',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationoperationlog',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='organizationoperationlog',
            name='target_user',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationConfig',
        ),
        migrations.DeleteModel(
            name='OrganizationOperationLog',
        ),
    ]
