# Generated by Django 5.1.7 on 2025-08-15 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_avatar_field"),
    ]

    operations = [
        # 添加新字段
        migrations.AddField(
            model_name='tag2',
            name='category',
            field=models.CharField(default='未分类', help_text='第一级分类，如：互联网、设计', max_length=100, verbose_name='行业分类'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag2',
            name='subcategory',
            field=models.CharField(default='未分类', help_text='第二级分类，如：java、UI设计', max_length=100, verbose_name='技术分类'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag2',
            name='specialty',
            field=models.CharField(blank=True, help_text='第三级分类，如：前端、后端', max_length=100, null=True, verbose_name='专业方向'),
        ),
        migrations.AddField(
            model_name='tag2',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='指向父级标签，用于构建层次结构', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user.tag2', verbose_name='父级标签'),
        ),
        migrations.AddField(
            model_name='tag2',
            name='level',
            field=models.PositiveSmallIntegerField(default=2, help_text='标签层级：2=行业-技术，3=行业-技术-岗位', verbose_name='层级'),
        ),
        # 修改现有字段
        migrations.AlterField(
            model_name='tag2',
            name='post',
            field=models.CharField(help_text='完整的岗位描述，如：互联网-java-前端', max_length=200, verbose_name='岗位描述'),
        ),
        # 删除旧字段
        migrations.RemoveField(
            model_name='tag2',
            name='subclasses',
        ),
        migrations.RemoveField(
            model_name='tag2',
            name='subdivision',
        ),
        migrations.RemoveField(
            model_name='tag2',
            name='zhuisu_id',
        ),
        migrations.RemoveField(
            model_name='tag2',
            name='required_number',
        ),
        # 添加新的索引和约束
        migrations.AlterModelOptions(
            name='tag2',
            options={'verbose_name': '能力标签', 'verbose_name_plural': '能力标签'},
        ),
        migrations.AlterUniqueTogether(
            name='tag2',
            unique_together={('category', 'subcategory', 'specialty')},
        ),
    ]
