# Generated by Django 5.2.5 on 2025-08-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_organizationoperationlog_organization_and_more'),
        ('user', '0009_redesign_tag2'),
    ]

    operations = [
    ]
