# Generated by Django 5.2.5 on 2025-08-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_merge_20250815_1906'),
    ]

    operations = [
        # 注释掉不存在的索引删除操作，避免KeyError
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_post_a2db1b_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_subclas_d05a44_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_zhuisu__248f08_idx',
        # ),
        migrations.AddIndex(
            model_name='tag2',
            index=models.Index(fields=['category'], name='tag_2_categor_585394_idx'),
        ),
        migrations.AddIndex(
            model_name='tag2',
            index=models.Index(fields=['subcategory'], name='tag_2_subcate_db5dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='tag2',
            index=models.Index(fields=['specialty'], name='tag_2_special_559d21_idx'),
        ),
        migrations.AddIndex(
            model_name='tag2',
            index=models.Index(fields=['parent'], name='tag_2_parent__9dac93_idx'),
        ),
        migrations.AddIndex(
            model_name='tag2',
            index=models.Index(fields=['level'], name='tag_2_level_2bd42a_idx'),
        ),
    ]
