# Generated by Django 5.2.5 on 2025-08-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_tag2_tag_2_post_a2db1b_idx_and_more'),
    ]

    operations = [
        # 注释掉不存在的索引删除操作，避免KeyError
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_post_a2db1b_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_subclas_d05a44_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_zhuisu__248f08_idx',
        # ),
        migrations.AlterField(
            model_name='tag2',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, help_text='标签层级：1=行业-技术，2=行业-技术-岗位', verbose_name='层级'),
        ),
    ]
