# Generated by Django 5.2.5 on 2025-08-16 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_tag2_tag_2_post_a2db1b_idx_and_more'),
    ]

    operations = [
        # 注释掉重复的索引删除操作，这些索引在0012中已经处理过
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_post_a2db1b_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_subclas_d05a44_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_zhuisu__248f08_idx',
        # ),
        migrations.AlterField(
            model_name='tag1stumatch',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='tag2stumatch',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='学生'),
        ),
    ]
