# Generated by Django 5.2.5 on 2025-08-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_tag2_tag_2_post_a2db1b_idx_and_more'),
    ]

    operations = [
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_post_a2db1b_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_subclas_d05a44_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_zhuisu__248f08_idx',
        # ),
    ]
