# Generated by Django 5.2.5 on 2025-08-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_tag2_tag_2_post_a2db1b_idx_and_more'),
    ]

    operations = [
        # 注释掉不存在的索引删除操作，这些索引在之前的迁移中已经处理过或不存在
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_post_a2db1b_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_subclas_d05a44_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_zhuisu__248f08_idx',
        # ),
    ]
