# Generated by Django 5.2.5 on 2025-08-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_remove_registration_number_field'),
        ('user', '0015_remove_tag2_tag_2_post_a2db1b_idx_and_more'),
    ]

    operations = [
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_post_a2db1b_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_subclas_d05a44_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_zhuisu__248f08_idx',
        # ),
        migrations.RenameIndex(
            model_name='organizationuser',
            new_name='org_user_perm_idx',
            old_name='organizatio_permiss_f1b3c7_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationuser',
            new_name='org_user_status_idx',
            old_name='organizatio_status_c580c7_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationuser',
            new_name='org_user_org_idx',
            old_name='organizatio_organiz_270ae8_idx',
        ),
        migrations.RenameIndex(
            model_name='tag1',
            new_name='tag1_value_idx',
            old_name='tag_1_value_6b2701_idx',
        ),
        migrations.RenameIndex(
            model_name='tag2',
            new_name='tag2_category_idx',
            old_name='tag_2_categor_585394_idx',
        ),
        migrations.RenameIndex(
            model_name='tag2',
            new_name='tag2_subcategory_idx',
            old_name='tag_2_subcate_db5dd2_idx',
        ),
        migrations.RenameIndex(
            model_name='tag2',
            new_name='tag2_specialty_idx',
            old_name='tag_2_special_559d21_idx',
        ),
        migrations.RenameIndex(
            model_name='tag2',
            new_name='tag2_parent_idx',
            old_name='tag_2_parent__9dac93_idx',
        ),
        migrations.RenameIndex(
            model_name='tag2',
            new_name='tag2_level_idx',
            old_name='tag_2_level_2bd42a_idx',
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['organization', 'permission'], name='org_user_org_perm_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['organization', 'status'], name='org_user_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tag2',
            index=models.Index(fields=['category', 'subcategory'], name='tag2_cat_subcat_idx'),
        ),
        migrations.AddIndex(
            model_name='tag2',
            index=models.Index(fields=['category', 'subcategory', 'specialty'], name='tag2_full_path_idx'),
        ),
    ]
