# Generated by Django 5.2.5 on 2025-08-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_tag2_tag_2_post_a2db1b_idx_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="tag1",
        #     name="created_at",
        # ),
        # migrations.RemoveField(
        #     model_name="tag1",
        #     name="updated_at",
        # ),
        # migrations.RemoveField(
        #     model_name="tag2",
        #     name="created_at",
        # ),
        # migrations.RemoveField(
        #     model_name="tag2",
        #     name="updated_at",
        # ),
    ]
