# Generated by Django 5.2.5 on 2025-08-26 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_add_organizationuser_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationuser',
            options={'verbose_name': '03-组织用户', 'verbose_name_plural': '03-组织用户'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '02-学生用户', 'verbose_name_plural': '02-学生用户'},
        ),
        migrations.AlterModelOptions(
            name='studentkeyword',
            options={'verbose_name': '06-学生关键词', 'verbose_name_plural': '06-学生关键词'},
        ),
        migrations.AlterModelOptions(
            name='tag1',
            options={'verbose_name': '04-兴趣标签', 'verbose_name_plural': '04-兴趣标签'},
        ),
        migrations.AlterModelOptions(
            name='tag1stumatch',
            options={'verbose_name': '07-学生兴趣标签关联', 'verbose_name_plural': '07-学生兴趣标签关联'},
        ),
        migrations.AlterModelOptions(
            name='tag2',
            options={'verbose_name': '05-能力标签', 'verbose_name_plural': '05-能力标签'},
        ),
        migrations.AlterModelOptions(
            name='tag2stumatch',
            options={'verbose_name': '08-学生能力标签关联', 'verbose_name_plural': '08-学生能力标签关联'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '01-用户总览', 'verbose_name_plural': '01-用户总览'},
        ),
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_post_a2db1b_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_subclas_d05a44_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_zhuisu__248f08_idx',
        # ),
        # migrations.RemoveField(
        #     model_name='tag1',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='tag1',
        #     name='updated_at',
        # ),
        # migrations.RemoveField(
        #     model_name='tag2',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='tag2',
        #     name='updated_at',
        # ),
    ]
