# Generated by Django 5.2.5 on 2025-08-31 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_organizationuser_options_alter_student_options_and_more'),
    ]

    operations = [
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_post_a2db1b_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_subclas_d05a44_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='tag2',
        #     name='tag_2_zhuisu__248f08_idx',
        # ),
        # migrations.RemoveField(
        #     model_name='tag1',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='tag1',
        #     name='updated_at',
        # ),
        # migrations.RemoveField(
        #     model_name='tag2',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='tag2',
        #     name='updated_at',
        # ),
    ]
