# Generated by Django 5.2.5 on 2025-09-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='标准名称')),
                ('description', models.TextField(verbose_name='标准描述')),
                ('status', models.CharField(choices=[('active', '启用'), ('archived', '归档')], db_index=True, default='active', max_length=20, verbose_name='状态')),
                ('is_template', models.BooleanField(db_index=True, default=False, help_text='标记为模板的评分标准可供其他需求复制使用', verbose_name='是否为模板')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '01-评分标准',
                'verbose_name_plural': '01-评分标准',
                'db_table': 'projectscore_evaluation_criteria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='指标名称')),
                ('description', models.TextField(blank=True, verbose_name='指标描述')),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='权重百分比，0-100之间', max_digits=5, verbose_name='权重（%）')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='最高分值')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必填')),
            ],
            options={
                'verbose_name': '02-评分指标',
                'verbose_name_plural': '02-评分指标',
                'db_table': 'projectscore_evaluation_indicator',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='得分')),
                ('comment', models.TextField(blank=True, verbose_name='评语')),
            ],
            options={
                'verbose_name': '04-指标评分',
                'verbose_name_plural': '04-指标评分',
                'db_table': 'projectscore_indicator_score',
            },
        ),
        migrations.CreateModel(
            name='ProjectEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('published', '已公示')], db_index=True, default='draft', max_length=20, verbose_name='评分状态')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='总分')),
                ('weighted_score', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='加权总分')),
                ('overall_comment', models.TextField(blank=True, verbose_name='总体评语')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公示时间')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='评分截止时间')),
            ],
            options={
                'verbose_name': '03-项目评分',
                'verbose_name_plural': '03-项目评分',
                'db_table': 'projectscore_project_evaluation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(db_index=True, verbose_name='排名')),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='最终得分')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='公示时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '05-项目排名',
                'verbose_name_plural': '05-项目排名',
                'db_table': 'projectscore_project_ranking',
                'ordering': ['rank'],
            },
        ),
    ]
