# Generated by Django 5.2.5 on 2025-09-13 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_initial'),
        ('projectscore', '0001_initial'),
        ('studentproject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcriteria',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_criteria', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria', to='organization.organization', verbose_name='所属组织'),
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='template_source',
            field=models.ForeignKey(blank=True, help_text='基于哪个模板创建的评分标准', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_criteria', to='projectscore.evaluationcriteria', verbose_name='模板来源'),
        ),
        migrations.AddField(
            model_name='evaluationindicator',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='projectscore.evaluationcriteria', verbose_name='评分标准'),
        ),
        migrations.AddField(
            model_name='indicatorscore',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='projectscore.evaluationindicator', verbose_name='评分指标'),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_evaluations', to='projectscore.evaluationcriteria', verbose_name='评分标准'),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='评分者'),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='last_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='最近修改人'),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='studentproject.studentproject', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='indicatorscore',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_scores', to='projectscore.projectevaluation', verbose_name='项目评分'),
        ),
        migrations.AddField(
            model_name='projectranking',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_rankings', to='projectscore.evaluationcriteria', verbose_name='评分标准'),
        ),
        migrations.AddField(
            model_name='projectranking',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='studentproject.studentproject', verbose_name='项目'),
        ),
        migrations.AddIndex(
            model_name='evaluationcriteria',
            index=models.Index(fields=['status'], name='projectscor_status_576cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationcriteria',
            index=models.Index(fields=['created_at'], name='projectscor_created_164c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationcriteria',
            index=models.Index(fields=['is_template', 'organization'], name='projectscor_is_temp_9359df_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationcriteria',
            index=models.Index(fields=['template_source', 'created_at'], name='projectscor_templat_5588a7_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationcriteria',
            index=models.Index(fields=['organization', 'status'], name='projectscor_organiz_694af7_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationindicator',
            index=models.Index(fields=['criteria', 'order'], name='projectscor_criteri_25658e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationindicator',
            unique_together={('criteria', 'name')},
        ),
        migrations.AddIndex(
            model_name='projectevaluation',
            index=models.Index(fields=['status'], name='projectscor_status_71410e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevaluation',
            index=models.Index(fields=['project', 'criteria'], name='projectscor_project_10c2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevaluation',
            index=models.Index(fields=['created_at'], name='projectscor_created_84cb25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectevaluation',
            unique_together={('project', 'criteria', 'evaluator')},
        ),
        migrations.AddIndex(
            model_name='indicatorscore',
            index=models.Index(fields=['evaluation', 'indicator'], name='projectscor_evaluat_29ae3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='indicatorscore',
            unique_together={('evaluation', 'indicator')},
        ),
        migrations.AddIndex(
            model_name='projectranking',
            index=models.Index(fields=['criteria', 'rank'], name='projectscor_criteri_8a3444_idx'),
        ),
        migrations.AddIndex(
            model_name='projectranking',
            index=models.Index(fields=['final_score'], name='projectscor_final_s_ee41fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectranking',
            unique_together={('project', 'criteria')},
        ),
    ]
