# Generated by Django 5.2.5 on 2025-09-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectscore', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='is_template',
            field=models.BooleanField(default=False, help_text='标记为模板的评分标准可供其他需求复制使用', verbose_name='是否为模板'),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='name',
            field=models.CharField(max_length=200, verbose_name='标准名称'),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='status',
            field=models.CharField(choices=[('active', '启用'), ('archived', '归档')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='evaluationindicator',
            name='name',
            field=models.CharField(max_length=100, verbose_name='指标名称'),
        ),
        migrations.AlterField(
            model_name='projectevaluation',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('published', '已公示')], default='draft', max_length=20, verbose_name='评分状态'),
        ),
        migrations.AlterField(
            model_name='projectranking',
            name='rank',
            field=models.PositiveIntegerField(verbose_name='排名'),
        ),
    ]
